### ISSUE TITLE
PH1. References

### ISSUE THREAD

**Issue by rslruiz** [lizardzoo/oo3GLanternProject#1]
Upload copy of references.

**Comment by BLACKTARHEROIN-tar** [comment]
Spring, L., Robillard, D., Gehlbach, L., & Moore Simas, T. A. (2011). Impact of pass/fail grading on medical students’ well‐being and academic outcomes. Medical education, 45(9), 867-877.

Fink, A. M. (2015). A comparative analysis of a standard based grading system versus a traditional based grading system with respect to student academic achievement and motivation (Doctoral dissertation, Concordia University Chicago).

Chiou, C. F., Hay, J. W., Wallace, J. F., Bloom, B. S., Neumann, P. J., Sullivan, S. D., ... & Ofman, J. J. (2003). Development and validation of a grading system for the quality of cost-effectiveness studies. Medical care, 32-44.

Sticca, F., Goetz, T., Bieg, M., Hall, N. C., Eberle, F., & Haag, L. (2017). Examining the accuracy of students’ self-reported academic grades from a correlational and a discrepancy perspective: Evidence from a longitudinal study. PloS one, 12(11), e0187367.

Shimizu, Y., Kamoi, S., Amada, S., Hasumi, K., Akiyama, F., & Silverberg, S. G. (1998). Toward the development of a universal grading system for ovarian epithelial carcinoma: I. Prognostic significance of histopathologic features—problems involved in the architectural grading system. Gynecologic oncology, 70(1), 2-12.

**Comment by rslruiz** [comment]
Upload copies of these references. Will you be using these references in your project?
